apiVersion: v1
kind: Service
metadata:
  name: medicure-service
spec:
  type: NodePort
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
